sudo: false

language: python

python:
    - 2.7

install:
    - pip install codecov
    - pip install pytest-cov
    - pip install pandas
    - pip install tensorflow

script:
    - py.test --cov=. tests/

after_success:
    - codecov
